export const GET_MOVIES = "GET_MOVIES";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const ADD_MOVIE = "ADD_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const GET_SINGLE_MOVIE = "GET_SINGLE_MOVIE";
export const GET_MOVIE_COUNT = "GET_MOVIE_COUNT";



export const GET_ACTORS = "GET_ACTORS";
export const DELETE_ACTOR = "DELETE_ACTOR";
export const ADD_ACTOR = "ADD_ACTOR";
export const UPDATE_ACTOR = "UPDATE_ACTOR";
export const GET_SINGLE_ACTOR = "GET_SINGLE_ACTOR";
export const GET_ACTOR_COUNT = "GET_ACTOR_COUNT"

export const GET_CATEGORIES = "GET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_SINGLE_CATEGORY = "GET_SINGLE_CATEGORY";

export const GET_CASTS = "GET_CASTS";
export const GET_SINGLE_CAST = "GET_SINGLE_CAST";

export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const ADD_COLLECTION = "ADD_COLLECTION";
export const UPDATE_COLLECTION = "UPDATE_COLLECTION";
export const GET_SINGLE_COLLECTION = "GET_SINGLE_COLLECTION";
export const GET_COLLECTION_COUNT = "GET_COLLECTION_COUNT"



// export const GET_CARS = "GET_CARS";
// export const DELETE_CAR = "DELETE_CAR";
// export const ADD_CAR = "ADD_CAR";
// export const UPDATE_CAR = "UPDATE_CAR";
// export const GET_SINGLE_CAR = "GET_SINGLE_CAR";

// //dropdown
export const GET_BY_MOVIE = "GET_BY_MOVIE";
export const GET_BY_ACTOR  = "GET_BY_ACTOR";
export const GET_BY_CATEGORY = "GET_BY_CATEGORY";
export const GET_BY_COLLECTION  = "GET_BY_COLLECTION";